### ISSUE TITLE
Dependency upgrade

### ISSUE THREAD

**Issue by ciapatakoza** [Samsung/CAS#2]
Hi, are there any plans to upgrade dependencies to more recent Ubuntu? The recent ubuntu operate on the linux kernel headers 6.5.0-28 which are way too and the `python2.7-numpy` is no more on recent distros.

**Comment by braton** [comment]
Hello,
I've pushed recent fixes to the repository. The README.md has been udpated, `python2.7-numpy` is no longer needed.
Please let me know in case of any further problems.
